version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: startup_investor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/startup_investor
      SECRET_KEY: your-super-secret-key-here-make-it-long-and-random-123456789
      ENVIRONMENT: development
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data: 